from __future__ import annotations

from typing import Any, Dict


DEFAULT_TEMPLATE_FAMILY_POLICY: Dict[str, Dict[str, Any]] = {
    "file_inspection_report": {
        "policy_class": "safe_read",
        "auto_finalize": True,
        "requires_review": False,
        "requires_confirmation": False,
        "inferred_tools": ["list_files", "save_artifact"],
        "required_permissions": ["filesystem.read", "artifact.write"],
    },
    "retrieval_report": {
        "policy_class": "safe_read",
        "auto_finalize": True,
        "requires_review": False,
        "requires_confirmation": False,
        "inferred_tools": ["retrieve_documents", "save_artifact"],
        "required_permissions": ["rag.read", "artifact.write"],
    },
    "metadata_search_report": {
        "policy_class": "safe_read",
        "auto_finalize": True,
        "requires_review": False,
        "requires_confirmation": False,
        "inferred_tools": ["search_metadata", "save_artifact"],
        "required_permissions": ["metadata.read", "artifact.write"],
    },
    "research_paper_search_operation": {
        "policy_class": "safe_read",
        "auto_finalize": True,
        "requires_review": False,
        "requires_confirmation": False,
        "inferred_tools": ["research_paper_search_tool"],
        "required_permissions": ["external_api.read"],
    },
    "content_patch": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["read_file", "patch_file", "save_artifact"],
        "required_permissions": ["filesystem.read", "filesystem.patch", "artifact.write"],
    },
    "content_replace": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["read_file", "write_file", "save_artifact"],
        "required_permissions": ["filesystem.read", "filesystem.write", "artifact.write"],
    },
    "gmail_read_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": False,
        "inferred_tools": ["mcp.gmail.search_messages"],
        "required_permissions": ["external_api.read"],
    },
    "gmail_draft_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["mcp.gmail.create_draft"],
        "required_permissions": ["external_api.write"],
        "fallback_capable_tools": ["mcp.gmail.create_draft"],
        "policy_expectations": [
            "confirmation required for outbound draft creation",
            "may use REST fallback if Gmail MCP rejects the draft create path",
        ],
    },
    "gmail_attachment_draft_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["mcp.gmail.create_draft_with_attachments"],
        "required_permissions": ["external_api.write", "artifact.read"],
        "fallback_capable_tools": ["mcp.gmail.create_draft_with_attachments"],
        "policy_expectations": [
            "confirmation required for outbound draft creation",
            "artifact-only attachments",
            "may use REST fallback if Gmail MCP rejects the draft create path",
        ],
    },
    "gmail_send_draft_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["mcp.gmail.send_draft"],
        "required_permissions": ["external_api.write"],
    },
    "gmail_send_message_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["mcp.gmail.send_message"],
        "required_permissions": ["external_api.write"],
    },
    "google_docs_read_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": False,
        "inferred_tools": ["mcp.gdocs.search_documents"],
        "required_permissions": ["external_api.read"],
    },
    "google_drive_read_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": False,
        "inferred_tools": ["mcp.gdrive.search_files"],
        "required_permissions": ["external_api.read"],
    },
    "google_drive_export_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": False,
        "inferred_tools": ["mcp.gdrive.download_file_content", "save_artifact"],
        "required_permissions": ["external_api.read", "artifact.write"],
        "fallback_capable_tools": ["mcp.gdrive.download_file_content"],
        "policy_expectations": [
            "downloaded content is saved as an app-scoped artifact",
            "may use REST fallback if Drive MCP rejects a readable file",
        ],
    },
    "google_drive_to_gmail_attachment_draft_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": [
            "mcp.gdrive.download_file_content",
            "save_artifact",
            "mcp.gmail.create_draft_with_attachments",
        ],
        "required_permissions": [
            "external_api.read",
            "artifact.write",
            "artifact.read",
            "external_api.write",
        ],
        "fallback_capable_tools": [
            "mcp.gdrive.download_file_content",
            "mcp.gmail.create_draft_with_attachments",
        ],
        "policy_expectations": [
            "confirmation required for outbound draft creation",
            "artifact-only attachments",
            "Drive downloads are saved as app-scoped artifacts before Gmail use",
            "may use REST fallback if Drive or Gmail MCP rejects supported operations",
        ],
    },
    "mcp_read_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": False,
        "inferred_tools": ["mcp.cms.search_pages"],
        "required_permissions": ["external_api.read"],
    },
    "mcp_write_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["mcp.cms.create_page"],
        "required_permissions": ["external_api.write"],
    },
    "adapter_build": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["site_build_adapter"],
        "required_permissions": ["adapter.execute"],
    },
    "adapter_transform": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": False,
        "inferred_tools": ["content_transform_adapter"],
        "required_permissions": ["adapter.execute"],
    },
    "notebooklm_list_notebooks_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": False,
        "inferred_tools": ["adapter.notebooklm.list_notebooks"],
        "required_permissions": ["external_api.read"],
    },
    "notebooklm_list_sources_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": False,
        "inferred_tools": ["adapter.notebooklm.list_sources"],
        "required_permissions": ["external_api.read"],
    },
    "notebooklm_ask_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": False,
        "inferred_tools": ["adapter.notebooklm.ask"],
        "required_permissions": ["external_api.read"],
    },
    "notebooklm_add_source_text_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["adapter.notebooklm.add_source_text"],
        "required_permissions": ["external_api.write"],
    },
    "notebooklm_add_source_url_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["adapter.notebooklm.add_source_url"],
        "required_permissions": ["external_api.write"],
    },
    "notebooklm_add_source_file_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["adapter.notebooklm.add_source_file"],
        "required_permissions": ["external_api.write"],
    },
    "notebooklm_generate_report_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["adapter.notebooklm.generate_report"],
        "required_permissions": ["external_api.write"],
    },
    "notebooklm_generate_slide_deck_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["adapter.notebooklm.generate_slide_deck"],
        "required_permissions": ["external_api.write"],
    },
    "notebooklm_generate_video_operation": {
        "policy_class": "review_required",
        "auto_finalize": False,
        "requires_review": True,
        "requires_confirmation": True,
        "inferred_tools": ["adapter.notebooklm.generate_video"],
        "required_permissions": ["external_api.write"],
    },
}


def get_template_family_policy(template_family: str) -> Dict[str, Any]:
    return DEFAULT_TEMPLATE_FAMILY_POLICY.get(template_family, {})
