import React from "react";
import { act, fireEvent, render, screen, waitFor } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

import ArtifactLibrary from "./ArtifactLibrary";

const styles = {
  card: {},
  executionLaneHeader: {},
  sectionTitle: {},
  small: {},
  formGrid: {},
  label: {},
  input: {},
  select: {},
  compactNote: {},
  actionRow: {},
  secondaryButton: {},
  inlineActionButton: {},
};

describe("ArtifactLibrary", () => {
  it("filters artifacts and delegates reuse and confirmed delete actions for the selected artifact", async () => {
    const onUseInNextStep = vi.fn();
    const onDeleteArtifact = vi.fn().mockResolvedValue(undefined);
    render(
      <ArtifactLibrary
        artifacts={[
          {
            artifact_id: "artifact_pdf",
            artifact_type: "google_drive_export",
            artifact_type_label: "Drive Export",
            display_name: "Execution Summary.pdf",
            summary: "Google Drive export: Execution Summary.pdf",
            mime_type: "application/pdf",
            created_at: "2026-06-11T09:30:00.000Z",
            routes: {
              preview: "/sessions/session-1/artifacts/artifact_pdf/preview?app_id=app-1&user_id=user-1",
              open: "/sessions/session-1/artifacts/artifact_pdf/file?app_id=app-1&user_id=user-1",
              delete: "/sessions/session-1/artifacts/artifact_pdf?app_id=app-1&user_id=user-1",
            },
            capabilities: {
              can_open: true,
              can_preview: true,
              can_delete: true,
              can_reuse: true,
            },
            file_info: {
              has_file: true,
              extension: ".pdf",
              size_bytes: 1024,
            },
            provenance: {
              source_label: "Generated by mcp.gdrive.download_file_content",
              source_session_id: "session-1",
            },
            debug: {
              artifact_id: "artifact_pdf",
              file_path: "D:\\exports\\Execution-Summary.pdf",
              metadata_path: "D:\\exports\\Execution-Summary.json",
            },
            consumption: {
              default_mode: "binary_payload",
              supported_modes: ["binary_payload", "file_backed", "metadata_only"],
            },
            eligible_consumers: ["gmail_attachments", "export"],
          },
          {
            artifact_id: "artifact_md",
            artifact_type: "chat_export",
            artifact_type_label: "Chat Export",
            display_name: "chat-export.md",
            summary: "Chat export",
            mime_type: "text/markdown",
            reviewed: true,
            routes: {
              open: "/sessions/session-1/artifacts/artifact_md/file?app_id=app-1&user_id=user-1",
              delete: "/sessions/session-1/artifacts/artifact_md?app_id=app-1&user_id=user-1",
            },
            capabilities: {
              can_open: false,
              can_preview: false,
              can_delete: true,
              can_reuse: true,
            },
            file_info: {
              has_file: false,
              extension: ".md",
              size_bytes: null,
            },
            debug: {
              artifact_id: "artifact_md",
              metadata_path: "D:\\exports\\chat-export.json",
            },
            consumption: {
              default_mode: "file_backed",
              supported_modes: ["file_backed", "inline_text", "metadata_only"],
            },
            eligible_consumers: ["export"],
          },
        ]}
        baseUrl="http://127.0.0.1:8012"
        onUseInNextStep={onUseInNextStep}
        onDeleteArtifact={onDeleteArtifact}
        styles={styles}
      />,
    );

    fireEvent.change(screen.getByLabelText("Artifact Search"), {
      target: { value: "summary" },
    });

    expect(screen.getAllByText(/execution summary\.pdf/i).length).toBeGreaterThan(0);
    expect(screen.queryByText(/chat-export\.md/i)).toBeNull();
    expect(screen.getAllByText(/drive export/i).length).toBeGreaterThan(0);
    expect(screen.getByRole("option", { name: "Drive Export" })).toBeInTheDocument();
    expect(screen.queryByRole("option", { name: "google_drive_export" })).toBeNull();
    expect(screen.getByRole("link", { name: /preview/i }).getAttribute("href")).toBe(
      "http://127.0.0.1:8012/sessions/session-1/artifacts/artifact_pdf/preview?app_id=app-1&user_id=user-1",
    );
    expect(screen.getByRole("link", { name: /open saved file/i }).getAttribute("href")).toBe(
      "http://127.0.0.1:8012/sessions/session-1/artifacts/artifact_pdf/file?app_id=app-1&user_id=user-1",
    );

    fireEvent.click(screen.getByRole("button", { name: /inspect/i }));
    expect(screen.getByText(/default reuse mode: binary payload/i)).toBeInTheDocument();
    expect(screen.getByText(/eligible consumers: gmail_attachments, export/i)).toBeInTheDocument();
    expect(screen.getByText(/source session: session-1/i)).toBeInTheDocument();
    expect(screen.getByText(/file type: \.pdf/i)).toBeInTheDocument();
    expect(screen.getByText(/debug details/i)).toBeInTheDocument();
    expect(screen.getByText(/artifact id: artifact_pdf/i)).toBeInTheDocument();

    fireEvent.click(screen.getByRole("button", { name: /reuse in composer/i }));
    expect(onUseInNextStep).toHaveBeenCalledWith(
      expect.objectContaining({
        artifact_id: "artifact_pdf",
        artifact_type: "google_drive_export",
      }),
      expect.objectContaining({}),
    );

    fireEvent.click(screen.getByRole("button", { name: /delete artifact/i }));
    expect(screen.getByText(/delete this artifact from the current session/i)).toBeInTheDocument();
    expect(onDeleteArtifact).not.toHaveBeenCalled();
    await act(async () => {
      fireEvent.click(screen.getByRole("button", { name: /confirm delete/i }));
    });
    expect(onDeleteArtifact).toHaveBeenCalledWith(
      expect.objectContaining({
        artifact_id: "artifact_pdf",
      }),
    );
  });

  it("shows reviewed and reuse mode badges for reviewed artifacts", () => {
    render(
      <ArtifactLibrary
        artifacts={[
          {
            artifact_id: "artifact_reviewed",
            artifact_type: "chat_export",
            artifact_type_label: "Chat Export",
            display_name: "Chat Export - Bible observation questions.md",
            summary: "Chat export from 2 selected messages.",
            mime_type: "text/markdown",
            reviewed: true,
            consumption: {
              default_mode: "file_backed",
              supported_modes: ["file_backed", "inline_text"],
            },
            capabilities: {
              can_open: false,
              can_preview: false,
              can_delete: true,
              can_reuse: true,
            },
            routes: {
              delete: "/sessions/session-1/artifacts/artifact_reviewed",
            },
          },
        ]}
        baseUrl="http://127.0.0.1:8012"
        onUseInNextStep={vi.fn()}
        onDeleteArtifact={vi.fn()}
        styles={styles}
      />,
    );

    expect(screen.getByText("Reviewed")).toBeInTheDocument();
    expect(screen.getByText("file backed")).toBeInTheDocument();
  });

  it("renders a close button when onClose is provided", () => {
    const onClose = vi.fn();
    render(
      <ArtifactLibrary
        artifacts={[
          {
            artifact_id: "artifact_pdf",
            artifact_type: "google_drive_export",
            display_name: "Execution Summary.pdf",
          },
        ]}
        onClose={onClose}
        styles={styles}
      />,
    );

    fireEvent.click(screen.getByRole("button", { name: /close/i }));
    expect(onClose).toHaveBeenCalledTimes(1);
  });

  it("shows unavailable actions when the backend marks an artifact file unavailable", () => {
    render(
      <ArtifactLibrary
        artifacts={[
          {
            artifact_id: "artifact_md",
            artifact_type: "chat_export",
            artifact_type_label: "Chat Export",
            display_name: "chat-export.md",
            capabilities: {
              can_open: false,
              can_preview: false,
              can_delete: true,
              can_reuse: true,
            },
            routes: {
              open: "/sessions/session-1/artifacts/artifact_md/file?app_id=app-1&user_id=user-1",
            },
          },
        ]}
        baseUrl="http://127.0.0.1:8012"
        styles={styles}
      />,
    );

    expect(screen.getByText(/preview unavailable/i)).toBeInTheDocument();
    expect(screen.getByText(/open unavailable/i)).toBeInTheDocument();
    expect(screen.queryByRole("link", { name: /open saved file/i })).toBeNull();
  });

  it("renders explicit loading, error, and empty-session states", () => {
    const { rerender } = render(
      <ArtifactLibrary
        artifacts={[]}
        loading
        styles={styles}
      />,
    );

    expect(screen.getByText(/loading session artifacts/i)).toBeInTheDocument();

    rerender(
      <ArtifactLibrary
        artifacts={[]}
        loading={false}
        error="Backend unavailable."
        styles={styles}
      />,
    );

    expect(screen.getByText(/unable to load artifacts: backend unavailable\./i)).toBeInTheDocument();

    rerender(
      <ArtifactLibrary
        artifacts={[]}
        loading={false}
        error=""
        styles={styles}
      />,
    );

    expect(screen.getByText(/no artifacts have been saved in this session yet/i)).toBeInTheDocument();
  });

  it("supports cancel and async error handling for delete confirmation", async () => {
    const onDeleteArtifact = vi.fn().mockRejectedValue(new Error("Delete failed."));
    render(
      <ArtifactLibrary
        artifacts={[
          {
            artifact_id: "artifact_pdf",
            artifact_type: "google_drive_export",
            display_name: "Execution Summary.pdf",
            capabilities: {
              can_delete: true,
              can_preview: true,
              can_open: true,
              can_reuse: true,
            },
            routes: {
              open: "/sessions/session-1/artifacts/artifact_pdf/file?app_id=app-1&user_id=user-1",
              preview: "/sessions/session-1/artifacts/artifact_pdf/preview?app_id=app-1&user_id=user-1",
            },
          },
        ]}
        baseUrl="http://127.0.0.1:8012"
        onDeleteArtifact={onDeleteArtifact}
        styles={styles}
      />,
    );

    fireEvent.click(screen.getByRole("button", { name: /delete artifact/i }));
    fireEvent.click(screen.getByRole("button", { name: /cancel delete/i }));
    expect(screen.queryByText(/delete this artifact from the current session/i)).toBeNull();
    expect(onDeleteArtifact).not.toHaveBeenCalled();

    fireEvent.click(screen.getByRole("button", { name: /delete artifact/i }));
    fireEvent.click(screen.getByRole("button", { name: /confirm delete/i }));
    expect(onDeleteArtifact).toHaveBeenCalledTimes(1);
    expect(await screen.findByText(/delete failed\./i)).toBeInTheDocument();
    await waitFor(() => expect(screen.getByRole("button", { name: /delete artifact/i })).toBeInTheDocument());
  });

  it("shows compatible next-step tools and passes a preferred target into reuse", () => {
    const onUseInNextStep = vi.fn();
    render(
      <ArtifactLibrary
        artifacts={[
          {
            artifact_id: "artifact_pdf",
            artifact_type: "google_drive_export",
            artifact_type_label: "Drive Export",
            display_name: "Execution Summary.pdf",
            mime_type: "application/pdf",
            capabilities: {
              can_open: true,
              can_preview: true,
              can_delete: true,
              can_reuse: true,
            },
            consumption: {
              default_mode: "binary_payload",
              supported_modes: ["binary_payload", "file_backed", "metadata_only"],
            },
          },
        ]}
        toolInventory={[
          {
            tool_id: "mcp.gmail.create_draft_with_attachments",
            name: "Gmail Create Draft With Attachments",
            artifact_picker: {
              enabled: true,
              field_name: "artifactIds",
              selection_mode: "multiple",
              accepted_artifact_types: ["google_drive_export"],
              allowed_mime_types: ["application/pdf"],
              required_consumption_mode: "binary_payload",
            },
          },
          {
            tool_id: "adapter.notebooklm.ask",
            name: "NotebookLM Ask",
            input_schema: { type: "object", properties: { question: { type: "string" } } },
          },
        ]}
        onUseInNextStep={onUseInNextStep}
        styles={styles}
      />,
    );

    fireEvent.click(screen.getByRole("button", { name: /inspect details/i }));
    expect(screen.getByText(/suggested next steps/i)).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: /use with gmail create draft with attachments/i }));

    expect(onUseInNextStep).toHaveBeenCalledWith(
      expect.objectContaining({
        artifact_id: "artifact_pdf",
      }),
      expect.objectContaining({
        preferredTargetId: "mcp.gmail.create_draft_with_attachments",
      }),
    );
  });

  it("recommends file-backed tools for compatible chat export artifacts", () => {
    const onUseInNextStep = vi.fn();
    render(
      <ArtifactLibrary
        artifacts={[
          {
            artifact_id: "artifact_chat_export",
            artifact_type: "chat_export",
            artifact_type_label: "Chat Export",
            display_name: "Chat Export.md",
            mime_type: "text/markdown",
            capabilities: {
              can_open: true,
              can_preview: true,
              can_delete: true,
              can_reuse: true,
            },
            consumption: {
              default_mode: "file_backed",
              supported_modes: ["file_backed", "inline_text", "metadata_only"],
            },
          },
        ]}
        toolInventory={[
          {
            tool_id: "adapter.notebooklm.add_source_file",
            name: "NotebookLM Add Source File",
            artifact_picker: {
              enabled: true,
              field_name: "filePath",
              selection_mode: "single",
              accepted_artifact_types: ["chat_export"],
              required_consumption_mode: "file_backed",
            },
          },
        ]}
        onUseInNextStep={onUseInNextStep}
        styles={styles}
      />,
    );

    expect(screen.getByText(/suggested next steps/i)).toBeInTheDocument();
    fireEvent.click(screen.getByRole("button", { name: /use with notebooklm add source file/i }));

    expect(onUseInNextStep).toHaveBeenCalledWith(
      expect.objectContaining({
        artifact_id: "artifact_chat_export",
      }),
      expect.objectContaining({
        preferredTargetId: "adapter.notebooklm.add_source_file",
      }),
    );
  });
});
